name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - run: yarn build
    - run: yarn test
    - run: yarn lint
    env:
        CI: 'true'
