name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: yarn install, build, test
      run: |
        yarn install
        yarn build
        yarn test
      env:
        CI: 'true'
